In [15]:
import pandas as pd
# 显示多行的执行信息
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
data = pd.read_csv(r"G:\临时3-8\网易云课堂《菜菜的机器学习sklearn课堂》\课件\03数据预处理和特征工程\Narrativedata.csv",
                  engine = 'python',
                   index_col = 0
                  )
data.head()

Age     Sex Embarked Survived
0  22.0    male        S       No
1  38.0  female        C      Yes
2  26.0  female        S      Yes
3  35.0  female        S      Yes
4  35.0    male        S       No

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 4 columns):
Age         714 non-null float64
Sex         891 non-null object
Embarked    889 non-null object
Survived    891 non-null object
dtypes: float64(1), object(3)
memory usage: 34.8+ KB


In [17]:
# 填充年龄的格式
Age = data.loc[:,'Age'].values.reshape(-1,1) # sklearn中的特征举证必须是二维的
from sklearn.impute  import SimpleImputer
imp_mean = SimpleImputer()  # 实例化。默认使用均值填补
imp_median = SimpleImputer(strategy = "median") # 利用中位数进行填补
imp_0 = SimpleImputer(strategy = "constant",fill_value = 0)


In [18]:
imp_mean = imp_mean.fit_transform(Age)
imp_median = imp_median.fit_transform(Age)
imp_0 = imp_0.fit_transform(Age)


array([[22.],
       [38.],
       [26.],
       [35.],
       [35.]])

array([[22.],
       [38.],
       [26.],
       [35.],
       [35.]])

In [20]:
imp_mean[:6]
imp_median[:6]
imp_0[:6]

array([[22.        ],
       [38.        ],
       [26.        ],
       [35.        ],
       [35.        ],
       [29.69911765]])

array([[22.],
       [38.],
       [26.],
       [35.],
       [35.],
       [28.]])

array([[22.],
       [38.],
       [26.],
       [35.],
       [35.],
       [ 0.]])

In [22]:
# 在这里我们使用种为主进行填补Age
data.loc[:,'Age'] = imp_median
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 4 columns):
Age         891 non-null float64
Sex         891 non-null object
Embarked    889 non-null object
Survived    891 non-null object
dtypes: float64(1), object(3)
memory usage: 34.8+ KB


In [23]:
# 使用众数填补 Embarked
Embarked = data.loc[:,"Embarked"].values.reshape(-1,1)
imp_mode = SimpleImputer(strategy = "most_frequent")
data.loc[:,"Embarked"] = imp_mode.fit_transform(Embarked)
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 4 columns):
Age         891 non-null float64
Sex         891 non-null object
Embarked    891 non-null object
Survived    891 non-null object
dtypes: float64(1), object(3)
memory usage: 34.8+ KB
